### ISSUE TITLE
Explanation about arguments

### ISSUE THREAD

**Issue by audjoselo** [anuradhawick/GraphPlas#2]
Hi, first, thank you for your work. My name is José and I am trying to use the script described to look out for the plasmid in two collections, one of Salmonella and the other of E. coli. However, I am having some problems understanding the script's arguments. What do you mean with: 
--classifier CLASSIFIER, -c CLASSIFIER
                        Classifier [pc or pf] default=pc
  --classification-file CLASSIFICATION_FILE, -f CLASSIFICATION_FILE
                        Path to classification file

Which of these options indicates the path to the origin fasta files?
 
 --output OUTPUT, -o OUTPUT
                        Contigs file (contigs.fasta)
This argument describes the output files' name, right?

I am starting in this field and my knowledge in bioinformatics is limited. So, Thanks in advance for your help

**Comment by anuradhawick** [comment]
Hi @audjoselo, 

This is a plasmid classification improvement tool.

As base classifiers, I expect plasclass or plasflow results to begin with. The `-c` parameter is the name of classifier (plasclass is pc and plasflow is pf). `--classification-file` is the output from plasclass or plasfow, depending on your classifier choice.

The origin fasta is obtained automatically from ` --spades-path`.

`--output` is the destination folder. GraphPlas creates a folder. I think it creates a text file with final result. I will update the help command right now. It does not output the `contigs.fasta` file. That is a mistake. Sorry about that.

Let me know if you face any more problems. Thanks

**Comment by audjoselo** [comment]
Hi @anuradhawick, thank you for your response. Up to I could understand, to use GraphPlas is necessary to install Plascope too right? I installed it and tried to use the following script indicating the path to Plascope installation:

GraphPlas.py --spades-path /home/audjoselo/carpeta2 --classifier pc --classification-file /home/audjoselo/soft-update/PlaScope-1.3.1 --output /home/audjoselo/carpeta2/Nueva --plots --ground-truth GROUND_TRUTH

However, I received the following error messages:
2022-07-27 10:32:48,147 - ERROR - One of the files were not found in the assembly path
2022-07-27 10:32:48,147 - ERROR - Ensure you have all the files: contigs.fasta, contigs.paths and assembly_graph_with_scaffolds.gfa

As I commented before, I am starting in the bioinformatic field. Maybe it is something basic, but I cannot identify what is wrong. I really appreciate any help you can provide.

**Comment by anuradhawick** [comment]
Hi, it is plasclass that we support. Not plascope. Let me know if you think we should support plascope. 

For spades path you need to give the output folder of metaspades assembly.  

You can skip ground truth argument. 

Feel free to ask any question you have.
